call step0_copy_bins.bat
call step1_create_OSTC4_firmware_upload_bin.bat
call step1_create_OSTC_RTE_upload.bat
call step1_create_OSTC_FontPack_upload.bat
call step2_create_OSTC4update_bin.bat
pause